#!/bin/sh

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2016-2018 kszaq (kszaquitto@gmail.com)
# Copyright (C) 2016-present AlexELEC (http://alexelec.in.ua)

################################################################################
# Colors
ESC_SEQ="\x1b["
COL_RESET=$ESC_SEQ"39;49;00m"
COL_RED=$ESC_SEQ"31;01m"
COL_YELLOW=$ESC_SEQ"33;01m"
COL_BLUE=$ESC_SEQ"34;01m"
################################################################################

IMAGE_KERNEL="/flash/kernel.img"
IMAGE_SYSTEM="/flash/SYSTEM"
IMAGE_DTB="/flash/dtb.img"
IMAGE_LOGO="/usr/share/bootloader/logo.img"
ACE_RUN="/storage/.cache/services/acestream.conf"
BACKUP_DATE=$(date +%Y%m%d%H%M%S)

install_to_nand() {
  if [ -f $IMAGE_KERNEL -a -f $IMAGE_SYSTEM ] ; then

    if grep -q /dev/system /proc/mounts ; then
      echo "Unmounting SYSTEM partiton."
      umount -f /dev/system
    fi
    mkdir -p /tmp/system

    mount -o rw,remount /flash

    read -p "Backup NAND to SD card? [y/N] " choice
    case "$choice" in
      [yY]*)
        if [ -e /dev/dtb ] ; then
          echo -n "Backing up device tree..."
          dd if=/dev/dtb of="/flash/dtb-$BACKUP_DATE.img" bs=256k conv=fsync 2> /dev/null
          echo "done."
        fi

        if [ -e /dev/recovery ] ; then
          echo -n "Backing up recovery partition..."
          dd if=/dev/recovery of="/flash/recovery-$BACKUP_DATE.img" bs=64k conv=fsync 2> /dev/null
          echo "done."
        fi

        if [ -e /dev/logo -a -e $IMAGE_LOGO ] ; then
          echo -n "Backing up logo partition..."
          dd if=/dev/logo of="/flash/logo-$BACKUP_DATE.img" bs=64k conv=fsync 2> /dev/null
          echo "done."
        fi
        ;;
      *)
        ;;
    esac

    echo -n "Formatting SYSTEM partition..."
    mke2fs -F -q -t ext4 -m 0 /dev/system || exit 1
    e2fsck -n /dev/system || exit 1
    echo "done."

    echo -n "Writing kernel image..."
    dd if="$IMAGE_KERNEL" of=/dev/boot bs=1M 2> /dev/null
    echo "done."

    echo -n "Copying SYSTEM files..."
    mount -o rw /dev/system /tmp/system
    cp $IMAGE_SYSTEM /tmp/system && sync
    umount /tmp/system
    echo "done."

    if [ -f $IMAGE_DTB ] ; then
      echo -n "Writing device tree image..."
      dd if=/dev/zero of=/dev/dtb bs=256k count=1 2> /dev/null
      dd if="$IMAGE_DTB" of=/dev/dtb bs=256k 2> /dev/null
      echo "done."
    fi

    if [ -f $IMAGE_LOGO ] ; then
      echo -n "Writing logo image..."
      dd if="$IMAGE_LOGO" of=/dev/logo bs=64k 2> /dev/null
      echo "done."
    fi

    read -p "Do you want to copy your user data to internal data partition? [Y/n] " choice
    case "$choice" in
      [nN]*)
        read -p "Do you want to format DATA partition? [Y/n] " choice
        case "$choice" in
          [nN]*)
            ;;
          *)
            echo -n "Formatting DATA partition..."
            mke2fs -F -q -t ext4 -m 0 /dev/data > /dev/null
            e2fsck -n /dev/data &> /dev/null
            echo "done."
        esac  
        ;;
      *)
        echo -n "Formatting DATA partition..."
        mke2fs -F -q -t ext4 -m 0 /dev/data > /dev/null
        e2fsck -n /dev/data &> /dev/null
        echo "done."

        if [ -f $ACE_RUN ] ; then
          echo -n "Stopping AceStream..."
          systemctl stop acestream
          echo "done."
        fi
        echo -n "Stopping Kodi..."
        systemctl stop kodi
        echo "done."
        echo "Copying user data..."
        mkdir -p /tmp/data
        mount -o rw /dev/data /tmp/data
        cp -pPRv /storage/. /tmp/data
        umount /tmp/data
        ;;
    esac

    echo ""
    echo -e "${COL_BLUE}All done!${COL_RESET}"
    echo -e "${COL_YELLOW}WARNING: If your internal memory layout is different from standard Amlogic, you have to reboot and perform this operation again!${COL_RESET}"
    echo ""
    echo -e "${COL_BLUE}Your system will reboot from internal memory.${COL_RESET}"
    echo ""

    read -p "Would you like to reboot now [y/N]? " choice
    case "$choice" in
      [yY]*)
        /usr/sbin/fw_setenv bootfromnand 1
        /usr/sbin/reboot switch_system
        ;;
      *)
        if [ -f $ACE_RUN ] ; then
          echo -n "Restarting AceStream..."
          systemctl start acestream
          echo "done."
        fi
        echo -n "Restarting Kodi..."
        systemctl start kodi
        echo "done."
        ;;
    esac

  else
    echo ""
    echo -e "${COL_RED}No AlexELEC image found on /flash! Exiting...${COL_RESET}"
    echo ""
  fi
}

if [ ! -e /dev/boot -o ! -e /dev/system -o ! -e /dev/data -o ! -e /dev/dtb ]; then
  echo ""
  echo -e "${COL_RED}One of BOOT, SYTEM, DATA or DTB partitions is missing.${COL_RESET}"
  echo -e "${COL_BLUE}Make sure that you are using a correct device tree and a device with internal memory!${COL_RESET}"
  echo "Not all devices are compatible with installtointernal due to unsupported NAND/eMMC"
  echo "chips being used by some manufacturers."
  exit 0
fi

echo ""
echo -e "${COL_RED}This script will erase BOOT, SYSTEM, DATA and DTB on your device${COL_RESET}"
echo -e "${COL_RED}and install AlexELEC that you booted from SD card/USB drive.${COL_RESET}"
echo ""
echo -e "${COL_YELLOW}It will create a backup of device tree and recovery partition on your boot media.${COL_RESET}"
echo -e "${COL_YELLOW}The script does not have any safeguards!${COL_RESET}"
echo ""
read -p "Type \"yes\" if you know what you are doing or anything else to exit: " choice
case "$choice" in
  yes) install_to_nand ;;
esac
