#!/bin/bash

# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2017-2018 Team LibreELEC (https://libreelec.tv)

# compile and copy amlogic autoscript files to part1
mcopy $RELEASE_DIR/3rdparty/bootloader/*autoscript :: 2>&1 > /dev/null || true

# creating Amlogic ZIP env-update package
if [ -a "$RELEASE_DIR/3rdparty/bootloader/aml_autoscript" ]; then
      echo "image: creating Amlogic ZIP env-update package"
      pushd $RELEASE_DIR/3rdparty/bootloader > /dev/null
      zip -q env-update.zip aml_autoscript
      echo "image: signing the env-update package"
      mkdir -p sign
      SIGNAPK_DIR="$ROOT/tools/signapk"
      java -Xmx1024m -jar $SIGNAPK_DIR/signapk.jar -w $SIGNAPK_DIR/testkey.x509.pem $SIGNAPK_DIR/testkey.pk8 env-update.zip sign/aml_autoscript.zip
      popd > /dev/null
      mcopy $RELEASE_DIR/3rdparty/bootloader/sign/aml_autoscript.zip ::
fi

# copy device trees to part1
for dtb in $RELEASE_DIR/3rdparty/bootloader/device_trees $RELEASE_DIR/3rdparty/bootloader/*.dtb ; do
  [ -e "$dtb" ] && mcopy -s "$dtb" ::
done
