#!/bin/bash

# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2009-2016 Stephan Raue (stephan@openelec.tv)
# Copyright (C) 2016-2018 Team LibreELEC (https://libreelec.tv)
# Copyright (C) 2018-present Team CoreELEC (https://coreelec.org)
# Copyright (C) 2011-present AlexELEC (http://www.alexelec.in.ua)

unset _CACHE_PACKAGE_LOCAL _CACHE_PACKAGE_GLOBAL _DEBUG_DEPENDS_LIST _DEBUG_PACKAGE_LIST

. config/options ""
. config/show_config

show_config
save_build_config

setup_toolchain target

$SCRIPTS/checkdeps

if [ -n "$CUSTOM_GIT_HASH" ]; then
  GIT_HASH="$CUSTOM_GIT_HASH"
else
  GIT_HASH=$(git rev-parse HEAD)
fi

if [ -n "$BUILDER_NAME" ]; then
  LIBREELEC_BUILD="$BUILDER_NAME"
else
  LIBREELEC_BUILD="origin"
fi

if [ -n "$CUSTOM_VERSION" ]; then
  LIBREELEC_VERSION="$CUSTOM_VERSION"
fi

if [ "$PROJECT" = "S805" -o "$PROJECT" = "S812" ]; then
  LIBREELEC_ARCH="$PROJECT.$DEVICE.$TARGET_ARCH"
elif [ "$PROJECT" = "Amlogic-dbl" ]; then
  LIBREELEC_ARCH="S9XX-DualBoot.$TARGET_ARCH"
else
  LIBREELEC_ARCH="S9XX.$TARGET_ARCH"
fi

TARGET_VERSION="$LIBREELEC_ARCH-$LIBREELEC_VERSION"
IMAGE_NAME="$DISTRONAME-$TARGET_VERSION"

if [ -n "$IMAGE_SUFFIX" ]; then
  IMAGE_NAME="$IMAGE_NAME-$IMAGE_SUFFIX"
fi

echo "$IMAGE_NAME" > $BUILD/BUILD_FILENAME

# setup fakeroot
rm -rf $FAKEROOT_SCRIPT   # remove $FAKEROOT_SCRIPT if it exist
touch $FAKEROOT_SCRIPT    # create an empty $FAKEROOT_SCRIPT
chmod +x $FAKEROOT_SCRIPT # make $FAKEROOT_SCRIPT executable

# clean old install dirs
rm -rf $INSTALL
rm -rf $STAMPS_INSTALL
mkdir -p $INSTALL

# create baselayout
for directory in etc dev proc run sys tmp usr var flash storage; do
  mkdir -p $INSTALL/$directory
done
ln -sf /var/media $INSTALL/media
ln -sf /usr/lib $INSTALL/lib
ln -sf /usr/bin $INSTALL/bin
ln -sf /usr/sbin $INSTALL/sbin

echo "$TARGET_VERSION" > $INSTALL/etc/release

# create /etc/os-release
echo -e "NAME=\"$DISTRONAME\"" > $INSTALL/etc/os-release
echo -e "VERSION=\"$LIBREELEC_VERSION\"" >> $INSTALL/etc/os-release
echo -e "ID=\"alexelec\"" >> $INSTALL/etc/os-release
echo -e "VERSION_ID=\"$OS_VERSION\"" >> $INSTALL/etc/os-release
echo -e "PRETTY_NAME=\"$DISTRONAME-$LIBREELEC_VERSION\"" >> $INSTALL/etc/os-release
echo -e "HOME_URL=\"http://alexelec.in.ua\"" >> $INSTALL/etc/os-release
echo -e "BUG_REPORT_URL=\"http://forum.alexelec.in.ua\"" >> $INSTALL/etc/os-release
echo -e "BUILD_ID=\"$GIT_HASH\"" >> $INSTALL/etc/os-release
echo -e "ALEXELEC_ARCH=\"$LIBREELEC_ARCH\"" >> $INSTALL/etc/os-release
echo -e "ALEXELEC_BUILD=\"$LIBREELEC_BUILD\"" >> $INSTALL/etc/os-release
echo -e "ALEXELEC_PROJECT=\"$PROJECT\"" >> $INSTALL/etc/os-release
[ -n "$DEVICE" ] && echo -e "ALEXELEC_DEVICE=\"$DEVICE\"" >> $INSTALL/etc/os-release
[ -n "$BUILDER_NAME" ] && echo -e "BUILDER_NAME=\"$BUILDER_NAME\"" >> $INSTALL/etc/os-release
[ -n "$BUILDER_VERSION" ] && echo -e "BUILDER_VERSION=\"$BUILDER_VERSION\"" >> $INSTALL/etc/os-release

# create /etc/issue
echo "$GREETING0" >  $INSTALL/etc/issue
echo "$GREETING1" >> $INSTALL/etc/issue
echo "$GREETING2" >> $INSTALL/etc/issue
echo "$GREETING3" >> $INSTALL/etc/issue
echo "$GREETING4" >> $INSTALL/etc/issue
echo "$DISTRONAME: $LIBREELEC_VERSION ($LIBREELEC_ARCH)" >> $INSTALL/etc/issue

ln -sf /etc/issue $INSTALL/etc/motd

PACKAGES_TO_BUILD="toolchain squashfs:host dosfstools:host fakeroot:host kmod:host mtools:host populatefs:host "
PACKAGES_TO_INSTALL="libc gcc linux linux-drivers linux-firmware $BOOTLOADER busybox util-linux corefonts network "

# Graphic support
[ ! "$DISPLAYSERVER" = "no" ] && PACKAGES_TO_INSTALL+="$DISPLAYSERVER "

# Multimedia support
[ ! "$MEDIACENTER" = "no" ] && PACKAGES_TO_INSTALL+="mediacenter "

# Sound support
[ "$ALSA_SUPPORT" = "yes" ] && PACKAGES_TO_INSTALL+="alsa "

# Automounter support
[ "$UDEVIL" = "yes" ] && PACKAGES_TO_INSTALL+="udevil "

# EXFAT support
[ "$EXFAT" = "yes" ] && PACKAGES_TO_INSTALL+="fuse-exfat "

# NTFS 3G support
[ "$NTFS3G" = "yes" ] && PACKAGES_TO_INSTALL+="ntfs-3g_ntfsprogs "

# Remote support
[ "$REMOTE_SUPPORT" = "yes" ] && PACKAGES_TO_INSTALL+="remote "

# Entware support
if [ "$ENTWARE_SUPPORT" = "yes" ]; then
  ln -sf /storage/.opt $INSTALL/opt
  PACKAGES_TO_INSTALL+="entware "
fi

# Install miscellaneous packages
PACKAGES_TO_INSTALL+="misc-packages "

# Virtual image creation support
[ "$PROJECT" = "Generic" ] && PACKAGES_TO_INSTALL+="virtual "

# Installer support
[ "$INSTALLER_SUPPORT" = "yes" ] && PACKAGES_TO_INSTALL+="installer "

# Devtools... (not for Release)
[ "$TESTING" = "yes" ] && PACKAGES_TO_INSTALL+="testing "

# Install gdb in all builds, including releases
PACKAGES_TO_INSTALL+="debug "

# OEM packages
[ "$OEM_SUPPORT" = "yes" ] && PACKAGES_TO_INSTALL+="oem "

# TVIP packages (for S805/812)
if [ "$TVIP_SUPPORT" = "yes" ]; then
  ln -sf /storage/.config/home $INSTALL/home
  PACKAGES_TO_INSTALL+="tvip "
fi

# Homebridge support
if [ "$HOMEBRIDGE_SUPPORT" = "yes" ]; then
  ln -sf /storage/.usr_local $INSTALL/usr/local
  PACKAGES_TO_INSTALL+="homebridge "
fi

PACKAGES_TO_BUILD+="$PACKAGES_TO_INSTALL"
$SCRIPTS/build_mt "$PACKAGES_TO_BUILD"

for package in $PACKAGES_TO_INSTALL; do
  $SCRIPTS/install "$package"
done

# copy PROJECT related files to filesystem
if [ -d "$PROJECT_DIR/$PROJECT/filesystem" ]; then
  cp -PR $PROJECT_DIR/$PROJECT/filesystem/* $INSTALL
  # install project specific systemd services
  for service in $PROJECT_DIR/$PROJECT/filesystem/usr/lib/systemd/system/*.service; do
    if [ -f "$service" ]; then
      enable_service $(basename $service)
    fi
  done
fi

# copy DEVICE related files to filesystem
if [ -n "$DEVICE" -a -d "$PROJECT_DIR/$PROJECT/devices/$DEVICE/filesystem" ]; then
  cp -PR $PROJECT_DIR/$PROJECT/devices/$DEVICE/filesystem/* $INSTALL
  # install device specific systemd services
  for service in $PROJECT_DIR/$PROJECT/devices/$DEVICE/filesystem/usr/lib/systemd/system/*.service; do
    if [ -f "$service" ]; then
      enable_service $(basename $service)
    fi
  done
fi

# run depmod for base overlay modules
MODVER=$(basename $(ls -d $INSTALL/usr/lib/kernel-overlays/base/lib/modules/*))
find $INSTALL/usr/lib/kernel-overlays/base/lib/modules/$MODVER/ -name *.ko | \
  sed -e "s,$INSTALL/usr/lib/kernel-overlays/base/lib/modules/$MODVER/,," \
    > $INSTALL/usr/lib/kernel-overlays/base/lib/modules/$MODVER/modules.order
$TOOLCHAIN/bin/depmod -b $INSTALL/usr/lib/kernel-overlays/base -a -e -F "$BUILD/linux-$(kernel_version)/System.map" $MODVER

# strip kernel modules
for MOD in $(find $INSTALL/usr/lib/kernel-overlays/ -type f -name *.ko); do
  ${TARGET_KERNEL_PREFIX}strip --strip-debug $MOD
done

# symlink overlayed modules to /usr/lib/modules
ln -sT /var/lib/modules $INSTALL/usr/lib/modules

# symlink overlayed firmware to /usr/lib/firmware
ln -sT /var/lib/firmware $INSTALL/usr/lib/firmware

# make target dir
mkdir -p $TARGET_IMG
rm -rf $TARGET_IMG/$IMAGE_NAME.kernel

# copy kernel to target dir
cp -PR $BUILD/linux-$(kernel_version)/arch/$TARGET_KERNEL_ARCH/boot/$KERNEL_TARGET $TARGET_IMG/$IMAGE_NAME.kernel
chmod 0644 $TARGET_IMG/$IMAGE_NAME.kernel

# Set mksquashfs options for each compression method
if [ -z "$SQUASHFS_COMPRESSION_OPTION" ]; then
  if [ "${SQUASHFS_COMPRESSION:-gzip}" = "gzip" ]; then
    SQUASHFS_COMPRESSION_OPTION="-Xcompression-level 9 -b 262144"
  elif [ "$SQUASHFS_COMPRESSION" = "lzo" ]; then
    SQUASHFS_COMPRESSION_OPTION="-Xcompression-level 9 -b 524288"
  elif [ "$SQUASHFS_COMPRESSION" = "zstd" ]; then
    SQUASHFS_COMPRESSION_OPTION="-Xcompression-level 22 -b 262144"
  fi
fi

# create squashfs file, default to gzip if no compression configured
echo "rm -rf \"$TARGET_IMG/$IMAGE_NAME.system\"" >> $FAKEROOT_SCRIPT
echo "$TOOLCHAIN/bin/mksquashfs \"$BUILD/image/system\" \"$TARGET_IMG/$IMAGE_NAME.system\" -noappend -comp ${SQUASHFS_COMPRESSION:-gzip} ${SQUASHFS_COMPRESSION_OPTION}" >> $FAKEROOT_SCRIPT

# run fakeroot
$TOOLCHAIN/bin/fakeroot -- $FAKEROOT_SCRIPT
rm -rf $FAKEROOT_SCRIPT
rm -rf $CURRENT_PKGBUILD

# set permissions
chmod 0644 $TARGET_IMG/$IMAGE_NAME.system

if [ "$1" = "release" -o "$1" = "mkimage" -o "$1" = "amlpkg" -o "$1" = "noobs" ]; then

  RELEASE_DIR="target/$IMAGE_NAME"

  # cleanup
  rm -rf $RELEASE_DIR

  # create release dir
  mkdir -p $RELEASE_DIR

  # remove n previous created release image
  rm -rf $TARGET_IMG/$IMAGE_NAME.img.gz

  if [ -n "$BOOTLOADER" ]; then

    BOOTLOADER_DIR="$(get_pkg_directory "$BOOTLOADER")"

    if [ -d $BOOTLOADER_DIR/files ]; then
      cp -R $BOOTLOADER_DIR/files/* $RELEASE_DIR
    fi

    if find_file_path bootloader/release $BOOTLOADER_DIR/release; then
      echo "Running $FOUND_PATH"
      . $FOUND_PATH
    fi
  fi

  cp $ROOT/README* $RELEASE_DIR
  cp $ROOT/CHANGELOG* $RELEASE_DIR
  echo "$TARGET_VERSION" > $RELEASE_DIR/RELEASE

  if [ ! "$MEDIACENTER" = "no" ]; then
    echo "Kodi commit: $(get_pkg_version $MEDIACENTER)" >> $RELEASE_DIR/RELEASE
  fi

  mkdir -p $RELEASE_DIR/licenses
  cp $ROOT/licenses/* $RELEASE_DIR/licenses

  mkdir -p $RELEASE_DIR/target
  cp $TARGET_IMG/$IMAGE_NAME.system $RELEASE_DIR/target/SYSTEM
  cp $TARGET_IMG/$IMAGE_NAME.kernel $RELEASE_DIR/target/KERNEL

  # create md5sum's
  ( cd $RELEASE_DIR;
    md5sum -t target/SYSTEM > target/SYSTEM.md5;
    md5sum -t target/KERNEL > target/KERNEL.md5;
  )

  # create target directory
  mkdir -p $TARGET_IMG

  # remove an previous created release tarball
  rm -rf $TARGET_IMG/$IMAGE_NAME.tar

  # create release tarball
  tar cf $TARGET_IMG/$IMAGE_NAME.tar -C target $IMAGE_NAME

  # create sha256 checksum of tarball
  #( cd $TARGET_IMG
  #  sha256sum ${IMAGE_NAME}.tar > ${IMAGE_NAME}.tar.sha256
  #)

  # create image files if requested
  if [[ ( "$1" = "amlpkg" || "$1" = "noobs" || "$1" = "mkimage" ) && -n "$BOOTLOADER" ]]; then
    # INSTALL_SRC_DIR can be board specific
    if [ -n "$DEVICE" -a -d "$PROJECT_DIR/$PROJECT/devices/$DEVICE/install" ]; then
      INSTALL_SRC_DIR="$PROJECT_DIR/$PROJECT/devices/$DEVICE/install"
    else
      INSTALL_SRC_DIR="$PROJECT_DIR/$PROJECT/install"
    fi

    # use processor count when no THREADS is defined
    if [ -z ${THREADS+x} ]; then
      THREADS="$(nproc)"
    fi
    if [ -n "$SUBDEVICES" ]; then
      SUBDEVICES+=" Generic"
      for SUBDEVICE in $SUBDEVICES;do
        # variables used in image script must be passed
        sem --no-notice -j${THREADS} env \
          PATH="$PATH:/sbin" \
          ROOT="$ROOT" \
          SCRIPTS="$SCRIPTS" \
          TOOLCHAIN="$TOOLCHAIN" \
          PROJECT_DIR="$PROJECT_DIR" \
          PROJECT="$PROJECT" \
          DEVICE="$DEVICE" \
          DISTRO="$DISTRO" \
          TARGET_IMG="$TARGET_IMG" \
          IMAGE_NAME="$IMAGE_NAME" \
          INSTALL_SRC_DIR="$INSTALL_SRC_DIR" \
          BOOTLOADER="$BOOTLOADER" \
          KERNEL_NAME="$KERNEL_NAME" \
          TARGET_KERNEL_ARCH="$TARGET_KERNEL_ARCH" \
          RELEASE_DIR=$RELEASE_DIR \
          UUID_STORAGE="$(uuidgen)" \
          DISTRO_BOOTLABEL="$DISTRO_BOOTLABEL" \
          DISTRO_DISKLABEL="$DISTRO_DISKLABEL" \
          UBOOT_SYSTEM="$UBOOT_SYSTEM" \
          UBOOT_VERSION="$UBOOT_VERSION" \
          EXTRA_CMDLINE="$EXTRA_CMDLINE" \
          SYSTEM_SIZE="$SYSTEM_SIZE" \
          SYSTEM_PART_START="$SYSTEM_PART_START" \
          SUBDEVICE=$SUBDEVICE \
          $SCRIPTS/mkimage
      done
      sem --no-notice --wait
    else
      # variables used in image script must be passed
      env \
        PATH="$PATH:/sbin" \
        ROOT="$ROOT" \
        SCRIPTS="$SCRIPTS" \
        TOOLCHAIN="$TOOLCHAIN" \
        PROJECT_DIR="$PROJECT_DIR" \
        PROJECT="$PROJECT" \
        DEVICE="$DEVICE" \
        DISTRO="$DISTRO" \
        TARGET_IMG="$TARGET_IMG" \
        IMAGE_NAME="$IMAGE_NAME" \
        INSTALL_SRC_DIR="$INSTALL_SRC_DIR" \
        BOOTLOADER="$BOOTLOADER" \
        KERNEL_NAME="$KERNEL_NAME" \
        TARGET_KERNEL_ARCH="$TARGET_KERNEL_ARCH" \
        RELEASE_DIR=$RELEASE_DIR \
        UUID_STORAGE="$(uuidgen)" \
        DISTRO_BOOTLABEL="$DISTRO_BOOTLABEL" \
        DISTRO_DISKLABEL="$DISTRO_DISKLABEL" \
        UBOOT_SYSTEM="$UBOOT_SYSTEM" \
        UBOOT_VERSION="$UBOOT_VERSION" \
        EXTRA_CMDLINE="$EXTRA_CMDLINE" \
        SYSTEM_SIZE="$SYSTEM_SIZE" \
        SYSTEM_PART_START="$SYSTEM_PART_START" \
        $SCRIPTS/mkimage
    fi
  fi

  # cleanup release dir
  rm -rf $RELEASE_DIR

  #cleanup unneeded files
  rm -rf $TARGET_IMG/$IMAGE_NAME.system $TARGET_IMG/$IMAGE_NAME.kernel
fi
